# Generated by Django 5.0.1 on 2024-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completedIA',
            field=models.BooleanField(null=True),
        ),
    ]
