# Generated by Django 5.0.1 on 2024-03-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='hobby1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='hobby2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='hobby3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='hobby4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
