# Generated by Django 5.0.1 on 2024-03-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='exercise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='meals',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='sleep_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='sleep_diff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='water',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
