# Generated by Django 5.0.1 on 2024-03-07 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userdetail_exercise_userdetail_meals_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.CharField(blank=True, max_length=100, null=True)),
                ('exercise', models.CharField(blank=True, max_length=100, null=True)),
                ('meals', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_diff', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
