# Generated by Django 5.0.1 on 2024-03-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_habit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='exercise',
            new_name='habit1',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='meals',
            new_name='habit2',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='sleep_amount',
            new_name='habit3',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='sleep_diff',
            new_name='habit4',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='water',
            new_name='habit5',
        ),
    ]
