# Generated by Django 5.0.1 on 2024-03-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_exercise_habit_habit1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='exercise',
            new_name='answer1',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='meals',
            new_name='answer2',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='sleep_amount',
            new_name='answer3',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='sleep_diff',
            new_name='answer4',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='water',
            new_name='answer5',
        ),
    ]
