# Generated by Django 5.0.1 on 2024-03-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_exercise_userdetail_answer1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='habit1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='habit2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='habit3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='habit4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='habit5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='mood',
            field=models.BooleanField(default=False),
        ),
    ]
