# Generated by Django 5.0.1 on 2024-03-07 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_useractivity_habit1_useractivity_habit2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('habit1', models.CharField(blank=True, max_length=100, null=True)),
                ('habit2', models.CharField(blank=True, max_length=100, null=True)),
                ('habit3', models.CharField(blank=True, max_length=100, null=True)),
                ('habit4', models.CharField(blank=True, max_length=100, null=True)),
                ('habit5', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
