# Generated by Django 5.0.1 on 2024-03-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_medication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitrecord',
            old_name='habit1',
            new_name='habit',
        ),
        migrations.RemoveField(
            model_name='habitrecord',
            name='habit2',
        ),
        migrations.RemoveField(
            model_name='habitrecord',
            name='habit3',
        ),
        migrations.RemoveField(
            model_name='habitrecord',
            name='habit4',
        ),
        migrations.RemoveField(
            model_name='habitrecord',
            name='habit5',
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='habitrecord',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
