# Generated by Django 5.0.1 on 2024-03-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_userprofile_lastassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
